name: firestore_stream
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-213.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.13.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
