// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJXtt6W-d4JcyDTmvAHmFKP0tjCKvu2Rs',
    appId: '1:512602551164:web:b0e925796896498e18aaf9',
    messagingSenderId: '512602551164',
    projectId: 'fir-2023-4f484',
    authDomain: 'fir-2023-4f484.firebaseapp.com',
    storageBucket: 'fir-2023-4f484.appspot.com',
    measurementId: 'G-ELKRJM7ZTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgNarZJH9eZfAFyXzoxP43Dii4seaXdoE',
    appId: '1:512602551164:android:e335eaade7f347cd18aaf9',
    messagingSenderId: '512602551164',
    projectId: 'fir-2023-4f484',
    storageBucket: 'fir-2023-4f484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClmIIoVAHrs0f-77lhgzpeWLik4K5ivW4',
    appId: '1:512602551164:ios:25e604ce5162935818aaf9',
    messagingSenderId: '512602551164',
    projectId: 'fir-2023-4f484',
    storageBucket: 'fir-2023-4f484.appspot.com',
    iosBundleId: 'com.example.firestoreStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClmIIoVAHrs0f-77lhgzpeWLik4K5ivW4',
    appId: '1:512602551164:ios:5036820e587e9eec18aaf9',
    messagingSenderId: '512602551164',
    projectId: 'fir-2023-4f484',
    storageBucket: 'fir-2023-4f484.appspot.com',
    iosBundleId: 'com.example.firestoreStream.RunnerTests',
  );
}
